version: "3.3"

services:
  api:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: $PORT
    ports:
      - 3030:3030
    depends_on:
      - nats
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=$PORT"
    networks:
      - internal

  opus.usdt.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: opus.usdt.exchange
    depends_on:
      - nats
    networks:
      - internal

  r1.eth.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r1.eth.exchange
    depends_on:
      - nats
    networks:
      - internal

  r1.opus.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r1.opus.exchange
    depends_on:
      - nats
    networks:
      - internal

  r1.usdt.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r1.usdt.exchange
    depends_on:
      - nats
    networks:
      - internal

  r2.eth.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r2.eth.exchange
    depends_on:
      - nats
    networks:
      - internal

  r2.opus.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r2.opus.exchange
    depends_on:
      - nats
    networks:
      - internal

  r2.usdt.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r2.usdt.exchange
    depends_on:
      - nats
    networks:
      - internal

  r3.eth.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r3.eth.exchange
    depends_on:
      - nats
    networks:
      - internal

  r3.opus.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r3.opus.exchange
    depends_on:
      - nats
    networks:
      - internal

  r3.usdt.exchange:
    image: jamesexchange/exchange-server
    env_file: docker-compose.env
    environment:      
      SERVICES: r3.usdt.exchange
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats:alpine3.14
    networks:
      - internal    

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
    ports:
      - $PORT:80
      - 443:443
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
  
networks:
  internal:
  default:

volumes:
  data:
